### PR TITLE
Ruby Project 4: Build test for spec tests

### PR DESCRIPTION
**Pull request by RailonA**
Buil test to make sure that all methods are working correctly.

### CODE REVIEW

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @RailonA and @RokoVarano, Excellent tests cases 👏 

Both of you have done well with the specs I must admit, however, it's required that 
your specs cover both positive and negative scenarios  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)) and you did excellently well on the positive ones.

Let's add a few negative scenarios and we will be done.
Say, there is spec for the wrong usage of a method \[e.g. `it "does not create the object if required attributes are missing"`\].

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Changes Requested 
**Great job :clap:in making some of the requested changes by the previous Tse,
However, there are a few changes to make to get this project approved.** 

- Two of the project test are failing on Rspec:

image
I can barely see negative tests or it's not properly defined. For the negative test, we can start to write like this:  it "does not create the object if required attributes are missing".

Kindly make the above changes and resubmit for another review.

You can contact me on slack, if you have any questions @enaburekhan.

Happy Coding!!! :blush:

**Review by MarilenaRoque — CHANGES_REQUESTED** [review]
# :rocket: Hello Micronauts!!!

We're almost there. You made an awesome job so far, but there is an important requirement not completed yet.

### Changes Required ♻️ 

- [x]  Use one _**it**_ block for each expected behavior. Do not test multiple aspects in one **_it_** block.
- Please, wrap each **expect** in one specific **it** block with a descriptive message about that specific case.

As you can check in the[ Pathwrigh](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/), in the "Project Specific" section, this is a requirement to complete that project. But more than that, It will let your code way more readable and modular and will help to understand what specific cases are being tested. That is why I need to request that change.

### Keep going with the awesome job! 💪🏻 

Feel free to message me on Slack, if you need flutter info about the review.
Happy Coding!!! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc.
[Portfolio](https://mariroqueproject.com/) | [Linkedin](https://www.linkedin.com/in/roquemarilena/) 
marilenas@id.uf.br_**

**Review by Georjane — APPROVED** [review]
## Status: PR Approved ✔️ ✔️
### Hi Team 🙌
Very nice work you have done with the Rspec testing on the Tic Tac Toe project. 
You have implemented all changes required by the previous Code Reviewers, and your project meets all requirements for approval. It's a thumbs up for me. 👍
You can go ahead and merge this PR. 

Goodluck on your next project and Happy Coding 💻

**Pull request merged**
